---
title: "BFI, MI : Comparison with Calculation by Hand"
author: "coop711"
date: "2025-05-12"
output: html_document
---

<!--
# Data Reading

`join()`을 사용하기 위하여 `dplyr` 패키지는 사전에 등록

```{r, plyr}
library(knitr)
library(pander)
library(magrittr)
library(dplyr)
panderOptions("table.split.table", Inf)
```

## 필수 자료 읽어들이기

```{r, data}
load("./BFI_MI_report_250512.RData")
str(BFI)
str(MI)
str(class_roll)
options(width = 180)
```
-->

## 컴퓨터 vs 손계산 점수 비교

```{r, echo = FALSE}
# kable(head(cbind(BFI_score_kr, BFI[paste(c("E", "N", "C", "A", "O"),"Score", sep = "_")])))
Manual_score_BFI <-
  BFI_score_kr %>%
  cbind(BFI[c("E", "N", "C", "A", "O")]) 
Manual_score_BFI[order(rownames(Manual_score_BFI)), ] %>%
  kable
```

## 컴퓨터 계산 등급 vs 손계산 등급

```{r, self, echo = FALSE, eval = TRUE}
Manual_grades_BFI <- 
  BFI_level_kr %>%
  cbind(BFI[paste(c("E", "N", "C", "A", "O"),"Score", sep = "_")]) 
Manual_grades_BFI[order(rownames(Manual_grades_BFI)), ] %>%
  kable(align = "c")
```

# 다중지능 점수 

## 컴퓨터 계산 점수 vs 손계산 점수

```{r, echo = FALSE}
Manual_scores_MI <- 
  cbind(MI_score_kr, MI[paste(LETTERS[1:8], "Score", sep = "_")])
Manual_scores_MI[order(rownames(Manual_scores_MI)), ] %>%
  kable
```