---
title: "BFI MI data : 241111"
author: "coop711"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(pander)
library(magrittr)
panderOptions("table.split.table", Inf)
knitr::opts_chunk$set(echo = TRUE)
```

# Data

## 출석부

```{r, xlsx}
library(readxl)
options(width = 180)
class_roll <- 
  read_excel("./data/class_roll241108.xlsx",
             range = "C1:D801",
             col_names = TRUE,
             col_types = "text")
class_roll %<>%
  data.frame
class_roll %<>%
  `names<-`(c("ID", "Name"))
class_roll$ID %<>%
  as.character
str(class_roll)
```

## BFI

```{r}
BFI <- "./data/BFI241111.xlsx" %>% 
  read_excel(range = "A1:AA729",
             col_names = TRUE)
BFI %<>%
  data.frame
BFI %<>%
  `names<-`(c("Time", "Email", "Dept", "ID", "Name", 
              "E1", "A1", "O1", "C1", "N1", "E2", "A2", "O2", "C2", "N2", "O3", "A3",
              "E", "N", "C", "A", "O", "E_Score", "N_Score", "C_Score", "A_Score", "O_Score"))
BFI$ID %<>%
  as.character
#> Likert Scale 값만 추출하여 숫자로 변환
BFI[6:17] %<>%
  sapply(FUN = {. %>% strsplit(split = "[.]") %>% sapply(`[`, 1)}) %>%
  as.numeric
# sapply(BFI[5:16], function(x){sapply(strsplit(x, split = "[.]"), `[`, 1)})
#> (R) 표시된 문항의 응답값을 역순으로 다시 계산
BFI[c("A2", "C2")] %<>% 
  `-` (6, .)
BFI %>% 
  head %>%
  kable
#> 구글 설문지를 사용하면서 필요없게된 코드이나 만약을 위하여
duplicated(BFI$ID) %>% 
  which %>%
  BFI[., c("ID", "Name")]
BFI[BFI$ID == "20242702", c("ID", "Name")]
BFI[BFI$ID == "20243020", c("ID", "Name")]
BFI <- BFI[-c(117, 598), ]
# BFI <- unique(BFI)
str(BFI)
#> ID 잘못 적은 친구
#> #> 학번 잘못 써서 고생시키는 녀석들 찾아내는 코드
wrong_id <- setdiff(BFI$ID, class_roll$ID)
BFI %>%
  filter(ID %in% wrong_id) %>%
  select(ID, Name)
# 1. 잘못된 id 가진 행 찾기
BFI_wrong_ids <- BFI %>%
  anti_join(class_roll, by = "ID") 
# 2. 잘못된 id를 따로 저장하고 수정하기
wrong_ids <- BFI_wrong_ids$ID
BFI_wrong_ids <- BFI_wrong_ids %>%
  mutate(ID = case_when(
    ID == "20245185" ~ "20245186",
    ID == "영어영문학과" ~ "20241236",
    ID == "20212546" ~ "20212549",
    ID == "202410197" ~ "20241097",
    ID == "사회복지학부" ~ "20242314",
    ID == "광고홍보학과" ~ "20192634",
    TRUE ~ ID
  ))
# 3. MI 에서 id 틀린 행을 제거하고 옳은 id 갖춘 행으로 교체하기
BFI <- BFI %>%
  filter(!ID %in% wrong_ids) %>%
  bind_rows(BFI_wrong_ids)
#> ID 잘못 적은 친구 수정사항 확인
BFI[BFI$ID %in% setdiff(BFI$ID, class_roll$ID), c("ID", "Name")]
#> "중간이다"를 도배한 친구 기록 삭제
# 동일한 값으로 일관된 응답을 입력한 사용자를 적발하는 함수
identify_uniform_responses <- function(data, uniform_value = "중간이다") {
  # 각 행이 특정 값으로만 일관되는지 확인
  uniform_rows <- apply(data, 1, function(row) all(row == uniform_value))
  
  # 일관된 응답을 입력한 행 번호 또는 ID 출력
  offenders <- which(uniform_rows) # 행 번호 
}

# 예시 데이터에 적용 (ID 열이 있다고 가정)
result <- identify_uniform_responses(BFI[, 6:17], "3")

# 결과 확인
print(result)   # 일관된 응답을 입력한 행 번호
print(BFI[result, c("ID", "Name")])    # 일관된 응답을 입력한 데이터
str(BFI)
BFI <- BFI[-result, ]
str(BFI)
#> 마감일로부터 제출시점의 기간
BFI_days <- as.numeric(difftime("2024-11-25 09:00:00", BFI$Time, 
                                 tz = "Asia/Seoul", units = 'days'))
BFI_hours <- as.numeric(difftime("2024-11-25 09:00:00", BFI$Time, 
                                 tz = "Asia/Seoul", units = 'hours'))
```

## MI

```{r}
MI <- "./data/MI241111.xlsx" %>% 
  read_excel(range = "A1:BQ721",
             col_names = TRUE)
MI %<>%
  data.frame
MI <- MI[, -2]
MI %<>%
  `names<-`(c("Time","Dept", "ID", "Name", 
              paste0(LETTERS[1:8], 1:56), 
              paste(LETTERS[1:8], "Score", sep = "_")))
# MI %<>%
#   `names<-`(c("Time", "Dept", "ID", "Name", 
#               paste0("Q", 1:56), 
#               paste(LETTERS[1:8], "Score", sep = "_")))
MI$ID %<>% 
  as.character
duplicated(MI$ID) %>% 
  which %>%
  MI[., c("ID", "Name")]
MI[MI$ID == "20242702", c("ID", "Name")]
MI <- MI[-109, ]
# MI <- unique(MI)
MI[5:60] %<>%
  sapply(FUN = {. %>% strsplit(split = "[.]") %>% sapply(`[`, 1)}) %>%
  as.numeric
# 동일한 값으로 일관된 응답을 입력한 사용자를 적발

# 예시 데이터에 적용 (ID 열이 있다고 가정)
result_M <- identify_uniform_responses(MI[, 5:60], "3")

# 결과 확인
print(result_M)   # 일관된 응답을 입력한 행 번호
print(MI[result_M, c("ID", "Name")])    # 일관된 응답을 입력한 데이터
str(MI)
# 부적절한 응답 삭제
MI <- MI[-result_M, ]
str(MI)
kable(head(MI[c(3, 5:18)]))
kable(head(MI[c(3, 19:32)]))
kable(head(MI[c(3, 33:46)]))
kable(head(MI[c(3, 47:60)]))
```

## 학번오류, 불참자

```{r}
#> 학번 잘못 써서 고생시키는 녀석들 찾아내는 코드
wrong_id <- setdiff(MI$ID, class_roll$ID)
MI %>%
  filter(ID %in% wrong_id) %>%
  select(ID, Name)
# 1. 잘못된 id 가진 행 찾기
MI_wrong_ids <- MI %>%
  anti_join(class_roll, by = "ID") 
# 2. 잘못된 id를 따로 저장하고 수정하기
wrong_ids <- MI_wrong_ids$ID
MI_wrong_ids <- MI_wrong_ids %>%
  mutate(ID = case_when(
    ID == "바이오메디컬" ~ "20243615",
    ID == "20233903" ~ "20243903",
    ID == "2024618" ~ "20246218",
    ID == "2024242220" ~ "20242420",
    ID == "2023390" ~ "20233930",
    ID == "20182929" ~ "20182919",
    TRUE ~ ID
  ))
# 3. MI 에서 id 틀린 행을 제거하고 옳은 id 갖춘 행으로 교체하기
MI <- MI %>%
  filter(!ID %in% wrong_ids) %>%
  bind_rows(MI_wrong_ids)
#> ID 잘못 적은 친구 수정사항 확인
MI[MI$ID %in% setdiff(MI$ID, class_roll$ID), c("ID", "Name")]
#> 각 조사 불참자 
# setdiff(class_roll$Name, BFI$Name)
# setdiff(class_roll$Name, MI$Name)
setdiff(BFI$ID, MI$ID) %>%
  `%in%`(BFI$ID, .) %>%
  `[`(BFI, ., c("ID", "Name")) %>%
  .[order(.$ID),]
setdiff(MI$ID, BFI$ID) %>%
  sort %>%
  `%in%`(MI$ID, .) %>%
  `[`(MI, ., c("ID", "Name")) %>%
  .[order(.$ID),]
# MI$Name
# class_roll$Name
str(MI)

#> 마감일로부터 제출시점의 기간
MI_days <- 
  as.numeric(difftime("2024-11-25 09:00:00", MI$Time, 
                      tz = "Asia/Seoul", units = 'days'))
MI_hours <- 
  as.numeric(difftime("2024-11-25 09:00:00", MI$Time, 
                      tz = "Asia/Seoul", units = 'hours'))
```

## Time

### BFI

```{r, echo = TRUE, eval = TRUE}
par(family = "KoPubWorldDotum Medium")
BFI_days %>%
  cut(breaks = c(0:14), include.lowest = TRUE) %>%
  table %>%
#  cbind("계" = rowSums(.)) %>%
#  rbind("계" = colSums(.)) %>%
  pander(caption = "일 단위")
BFI_days %>%
  cut(breaks = c(0:14), include.lowest = TRUE) %>%
  table %>%
  chisq.test %>%
  pander
BFI_days %>%
  cut(breaks = c(0:14), include.lowest = TRUE) %>%
  table %>%
  rev %>%
  barplot(space = 0, 
          names.arg = rep(c("월", "화", "수", "목", "금", "토", "일"), 2), 
          col = c(rep("white", 13), "pink"))
title(main = "일 단위 BFI 제출 횟수")
```

### MI

```{r, echo = TRUE, eval = TRUE}
par(family = "KoPubWorldDotum Medium")
MI_days %>%
  cut(breaks = c(0:14), include.lowest = TRUE) %>%
  table %>%
#  cbind("계" = rowSums(.)) %>%
#  rbind("계" = colSums(.)) %>%
  pander(caption = "일 단위")
MI_days %>%
  cut(breaks = c(0:14), include.lowest = TRUE) %>%
  table %>%
  chisq.test %>%
  pander
MI_days %>%
  cut(breaks = c(0:14), include.lowest = TRUE) %>%
  table %>%
  rev %>%
  barplot(space = 0, 
          names.arg = rep(c("월", "화", "수", "목", "금", "토", "일"), 2), 
          col = c(rep("white", 13), "pink"))
title(main = "일 단위 MI 제출 횟수")
```

## Working Data

```{r, echo = TRUE}
BFI <- BFI[, -c(3, 5)]
MI <- MI[, -c(2, 4)]
## piping을 이용한 다음 대안들을 개선해 보세요.
# lapply(list(1:15, c(1, 16:29), c(1, 30:43), c(1, 44:57)), 
#        function(x) MI %>% `[`(x) %>% head %>% kable)
# list(1:15, c(1, 16:29), c(1, 30:43), c(1, 44:57)) %>%
#   lapply(function(x) MI %>% `[`(x) %>% head %>% kable)
# list(1:15, c(1, 16:29), c(1, 30:43), c(1, 44:57)) %>%
#   lapply(. %>% {kable(head(MI[.]))})

```

### Save Data

```{r, save.image}
saveRDS(BFI, file = "./BFI241111.RDS")
saveRDS(MI, file = "./MI241111.RDS")
save.image("./BFI_MI_241111.RData")
```

